<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sparkasse.Client.Common</RootNamespace>
    <AssemblyName>Sparkasse.Client.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="ADaxer.MvvmNav.Core" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
