# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:7002
@Email = administrator@localhost
@Password = Administrator1!
@AccessToken = CfDJ8D8A96JhYs9Fhg4ZtsTXXB3T81JoaI7SZGh8rLlDxCSg6lOPdzFqVP_o3rj661yZh7Ay7oqn6MSh6XEVIde_26VEEjERztapR8F6OufphIR3klCQEWoxu5eXckWnCQwrIb1cWQ_hkoGa-NrBbSaQNvEEs2lfh0Oi3NzHXIchDg83rFU7k1EwLfIjaVy-Y4Sh7pkg0TwiBH1c4NATZmGcAMZjEfooH9feqTX-PoMmvYyMDyIe5Wme5Fx9iKdM1bYi8L3InzQOKx5EunveRZf2iHTU-nzl4iO-OB_xBkfcFBQrSgQ7AYAgzmrN1u8dX_I-6yX7a3FqHCBFAxwfdF9j-RA-m4yv7ygBrf-wAt6V-tjEzHtjQg7DsUeFi1vtLJypdJeYQyIEIHG7XGF8P065ZUeJFWbS6MAAktayl43qXMZOvqfgOMjguT-DYM1TJyxEgfgKfj4RXwsPyJfj72DtqT-NQ6oOHPyFLM7BDiAUUwKswUcD3FTf3u8r2tKB7F5QzMCidF3Menw2maeHZRFCUqf4O1iCF9_Zte1qwR-Y58uaWPphCtiJVdBNlCO-fMzSir97uQxHKuA5x_uKaZqrjF3D5vxmxp-sxbzR3bhZqjlddFi9D6SrxmngWax1DZT7jdHWXk7RiQgNeMp-3JnE5Js50cdWF6qzHD_b9PSioCXsf35yKkZ-Z8wMj0vmOhik5B46R7YbuBv7xRyRJrEfiX0QCFQAI5h0a2M3eyTSrOGJfJPZdNkDHRZ1Nh8OocS2ckzLnkzJHjwS68VZRubhI2dHI8v2rkwvHX5aKJrMgoDJmw2NHw88sAmNRxZAA-D7eg
###

# POST Register new user
# Register a new user account
POST {{Web_HostAddress}}/api/Users/register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Login
# Login with username and password to get an access token
# @name login
POST {{Web_HostAddress}}/api/Users/login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Refresh Token
# Use refresh token to get a new access token
POST {{Web_HostAddress}}/api/Users/refresh
Content-Type: application/json

{
  "refreshToken": "{{$dotenv REFRESH_TOKEN}}"
}

###

# POST Logout
# Logout current user
POST {{Web_HostAddress}}/api/Users/logout
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{AccessToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{AccessToken}}

###

#GET TodoList
GET {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{AccessToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{AccessToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}
Authorization: Bearer {{AccessToken}}

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{AccessToken}}

###

########################################
# BankAccounts Endpoints
########################################

@AccountId = 7041468d-52f2-4a24-9747-175f43f4191d

# POST Open Bank Account
POST {{Web_HostAddress}}/api/BankAccounts
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "initialBalance": 1000.00
}

###

# POST Deposit Money
POST {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/deposit?amount=250.00
Authorization: Bearer {{AccessToken}}

###

# POST Withdraw Money
POST {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/withdraw?amount=100.00
Authorization: Bearer {{AccessToken}}

###

# POST Withdraw Money wrong id
POST {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/withdraw?amount=100.00
Authorization: Bearer {{AccessToken}}

###

# GET Account Balance
GET {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/balance
Authorization: Bearer {{AccessToken}}

###

# GET Account Statement
GET {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/statement
Authorization: Bearer {{AccessToken}}

###

# DELETE Close Account
DELETE {{Web_HostAddress}}/api/BankAccounts/{{AccountId}}/close
Authorization: Bearer {{AccessToken}}

###